---
version: "3"
services:
  cloudjobs_database:
    image: mongo
  cloudjobs_application:
    image: cloudjobs_app:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on: 
      - "cloudjobs_database"
    environment:
      - ITJOBS_KEY=01ad8778ca89c4e7fc31549279a7630d
      - ITJOBS_URL=http://api.itjobs.pt
      - SERVICE_DB_HOSTNAME=cloudjobs_database
      - SERVICE_DB_PORT=27017
