---
version: "3"
services:
  cloudjobs_database:
    image: mongo
  cloudjobs_application:
    image: cloudjobs_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/app/backend
      - ./frontend:/var/app/frontend
    ports:
      - "8080:10000"
    depends_on: 
      - "cloudjobs_database"
    environment:
      - IT_JOBS_ITJOBS_KEY=<key>
      - IT_JOBS_URL=http://api.itjobs.pt
      - DB_HOST=cloudjobs_database

# docker-compose up --build